"""Simple statistical augmentation for cold-start forecasting.

The method in this module is intentionally modest and interpretable. It assumes
that a short training series can be approximated by a linear trend plus
Gaussian residual noise. Synthetic values are generated by extending that
training-only trend and sampling noise with the training residual standard
deviation.
"""

from __future__ import annotations

import math
import random
from collections.abc import Sequence


def generate_statistical_synthetic_series(
    train_series: Sequence[float],
    n_synthetic_points: int,
    random_seed: int = 42,
) -> list[float]:
    """Generate synthetic continuation values from a training-only trend model.

    Assumptions:
    - The short training window is represented as a linear trend plus noise.
    - Future synthetic points extend the fitted training trend.
    - Residual variation is approximated by Gaussian noise with standard
      deviation estimated only from training residuals.

    The function does not accept test data and therefore cannot directly leak
    future observations into the synthetic series.
    """
    values = _validate_train_series(train_series)
    _validate_n_synthetic_points(n_synthetic_points)

    slope, intercept = _fit_linear_trend(values)
    fitted_values = [intercept + slope * index for index in range(len(values))]
    residuals = [observed - fitted for observed, fitted in zip(values, fitted_values)]
    residual_std = _sample_standard_deviation(residuals)

    rng = random.Random(random_seed)
    synthetic_values = []
    for index in range(len(values), len(values) + n_synthetic_points):
        trend_value = intercept + slope * index
        noise = rng.gauss(0.0, residual_std) if residual_std > 0 else 0.0
        synthetic_values.append(trend_value + noise)

    return synthetic_values


def _fit_linear_trend(values: list[float]) -> tuple[float, float]:
    """Fit y = intercept + slope * t using ordinary least squares."""
    if len(values) == 1:
        return 0.0, values[0]

    x_values = list(range(len(values)))
    x_mean = sum(x_values) / len(x_values)
    y_mean = sum(values) / len(values)
    numerator = sum((x - x_mean) * (y - y_mean) for x, y in zip(x_values, values))
    denominator = sum((x - x_mean) ** 2 for x in x_values)
    slope = numerator / denominator if denominator else 0.0
    intercept = y_mean - slope * x_mean
    return slope, intercept


def _sample_standard_deviation(values: list[float]) -> float:
    """Estimate sample standard deviation for residual noise."""
    if len(values) < 2:
        return 0.0

    mean_value = sum(values) / len(values)
    variance = sum((value - mean_value) ** 2 for value in values) / (len(values) - 1)
    return math.sqrt(variance)


def _validate_train_series(train_series: Sequence[float]) -> list[float]:
    if isinstance(train_series, (str, bytes)):
        raise TypeError("train_series must be a numeric sequence, not a string")

    try:
        values = [float(value) for value in train_series]
    except TypeError as exc:
        raise TypeError("train_series must be an iterable numeric sequence") from exc
    except ValueError as exc:
        raise ValueError("train_series must contain only numeric values") from exc

    if not values:
        raise ValueError("train_series must contain at least one observation")
    for value in values:
        if not math.isfinite(value):
            raise ValueError("train_series must contain only finite values")

    return values


def _validate_n_synthetic_points(n_synthetic_points: int) -> None:
    if not isinstance(n_synthetic_points, int):
        raise TypeError("n_synthetic_points must be an integer")
    if n_synthetic_points <= 0:
        raise ValueError("n_synthetic_points must be a positive integer")
