"""Endpoint-preserving statistical augmentation for cold-start forecasting.

Synthetic histories occupy the same time indices as the observed training
window.  They are therefore alternative training histories, not invented
future observations.  Each history is generated by residual bootstrapping and
is linearly adjusted to retain the observed first and last values.
"""

from __future__ import annotations

import math
import random
from collections.abc import Sequence
from collections.abc import Callable

ForecastFunction = Callable[[list[float], int], list[float]]


def generate_endpoint_preserving_histories(
    train_series: Sequence[float],
    n_synthetic_series: int,
    random_seed: int = 42,
) -> list[list[float]]:
    """Generate aligned synthetic histories using training data only.

    Residuals around a fitted linear trend are sampled with replacement.  A
    linear correction then anchors both endpoints to the real history, so the
    synthetic observations never extend beyond the forecast origin.
    """
    values = _validate_train_series(train_series)
    _validate_n_synthetic_series(n_synthetic_series)

    if len(values) == 1:
        return [values.copy() for _ in range(n_synthetic_series)]

    slope, intercept = _fit_linear_trend(values)
    fitted_values = [intercept + slope * index for index in range(len(values))]
    residuals = [observed - fitted for observed, fitted in zip(values, fitted_values)]

    rng = random.Random(random_seed)
    histories: list[list[float]] = []
    last_index = len(values) - 1
    for _ in range(n_synthetic_series):
        raw = [fitted + rng.choice(residuals) for fitted in fitted_values]
        start_delta = values[0] - raw[0]
        end_delta = values[-1] - raw[-1]
        aligned = [
            value + start_delta + (end_delta - start_delta) * index / last_index
            for index, value in enumerate(raw)
        ]
        histories.append(aligned)

    return histories


def augmented_ensemble_forecast(
    train_series: Sequence[float],
    forecast_horizon: int,
    forecast_function: ForecastFunction,
    n_synthetic_series: int,
    random_seed: int = 42,
) -> list[float]:
    """Average forecasts from the real and aligned synthetic histories."""
    values = _validate_train_series(train_series)
    histories = generate_endpoint_preserving_histories(
        values, n_synthetic_series, random_seed
    )
    forecasts = [forecast_function(values, forecast_horizon)]
    forecasts.extend(forecast_function(history, forecast_horizon) for history in histories)
    return [sum(values_at_step) / len(forecasts) for values_at_step in zip(*forecasts)]


def _fit_linear_trend(values: list[float]) -> tuple[float, float]:
    """Fit y = intercept + slope * t using ordinary least squares."""
    if len(values) == 1:
        return 0.0, values[0]

    x_values = list(range(len(values)))
    x_mean = sum(x_values) / len(x_values)
    y_mean = sum(values) / len(values)
    numerator = sum((x - x_mean) * (y - y_mean) for x, y in zip(x_values, values))
    denominator = sum((x - x_mean) ** 2 for x in x_values)
    slope = numerator / denominator if denominator else 0.0
    intercept = y_mean - slope * x_mean
    return slope, intercept


def _validate_train_series(train_series: Sequence[float]) -> list[float]:
    if isinstance(train_series, (str, bytes)):
        raise TypeError("train_series must be a numeric sequence, not a string")

    try:
        values = [float(value) for value in train_series]
    except TypeError as exc:
        raise TypeError("train_series must be an iterable numeric sequence") from exc
    except ValueError as exc:
        raise ValueError("train_series must contain only numeric values") from exc

    if not values:
        raise ValueError("train_series must contain at least one observation")
    for value in values:
        if not math.isfinite(value):
            raise ValueError("train_series must contain only finite values")

    return values


def _validate_n_synthetic_series(n_synthetic_series: int) -> None:
    if not isinstance(n_synthetic_series, int):
        raise TypeError("n_synthetic_series must be an integer")
    if n_synthetic_series <= 0:
        raise ValueError("n_synthetic_series must be a positive integer")
